export interface TranscriptMetadata {
  wordCount: number;
  duration: number; // seconds
  language: string;
  hasTranslation: boolean;
}

export function generateTranscriptFilename(title: string, format: "txt" | "pdf" | "docx" = "txt"): string {
  const timestamp = new Date().toISOString().split("T")[0];
  const sanitized = title.replace(/[^\w\-]/g, "-").toLowerCase().slice(0, 50);
  return `${sanitized}_${timestamp}.${format}`;
}

export function calculateTranscriptStats(text: string): TranscriptMetadata {
  const words = text.split(/\s+/).filter((w) => w.length > 0);
  const estimatedDuration = Math.ceil((words.length / 130) * 60); // 130 WPM average

  return {
    wordCount: words.length,
    duration: estimatedDuration,
    language: "en",
    hasTranslation: false,
  };
}

export async function exportTranscriptAsText(
  title: string,
  content: string,
  translation?: string
): Promise<string> {
  let exported = `${title}\n${"=".repeat(title.length)}\n\n`;
  exported += `Original:\n${content}\n\n`;

  if (translation) {
    exported += `Translation:\n${translation}\n\n`;
  }

  exported += `\nGenerated by Last Minutes on ${new Date().toISOString()}`;

  return exported;
}

export async function exportTranscriptAsJSON(
  title: string,
  originalText: string,
  translatedText?: string,
  metadata?: Record<string, unknown>
): Promise<string> {
  const data = {
    title,
    originalText,
    translatedText,
    metadata: {
      generatedAt: new Date().toISOString(),
      ...metadata,
    },
  };

  return JSON.stringify(data, null, 2);
}

export function truncateTranscript(text: string, maxWords: number = 100): string {
  const words = text.split(/\s+/);
  if (words.length <= maxWords) return text;
  return words.slice(0, maxWords).join(" ") + "...";
}

export function highlightSearchTerms(text: string, terms: string[]): string {
  let highlighted = text;
  terms.forEach((term) => {
    const regex = new RegExp(`(${term})`, "gi");
    highlighted = highlighted.replace(regex, "<mark>$1</mark>");
  });
  return highlighted;
}
